### PR TITLE
fix cors with safari

### PR DESCRIPTION
**Pull request by devoncarew**
@lukechurch, I think this will fix a cors issue with safari. The site can't analyze or compile - some googling led me to believe that we need to add the allow-control-headers for `Content-Type`.

### CODE REVIEW

**Comment by lukechurch** [comment]
@devoncarew good catch, thanks. 

ok - I think in this case I'll strip GET and OPTIONs as verbs, since we don't support them on the server anyway, or did your googling suggest they were required?

**Comment by devoncarew** [comment]
No, sounds good - they were copied from a local server example.

**Comment by devoncarew** [comment]
(updated w/ the GET and OPTIONS permissions removed)

**Comment by lukechurch** [comment]
lgtm

**Pull request merged**
